"""Subclass of Home_Frame_2, which is generated by wxFormBuilder."""

import wx
import Stock_Monitor

# Implementing Home_Frame_2
class Stock_Monitoring_SystemHome_Frame_2( Stock_Monitor.Home_Frame_2 ):
	def __init__( self, parent ):
		Stock_Monitor.Home_Frame_2.__init__( self, parent )
	
	# Handlers for Home_Frame_2 events.
	def ExitOnButtonClick( self, event ):
		# TODO: Implement ExitOnButtonClick
		pass
	
	def onLogin( self, event ):
		# TODO: Implement onLogin
		pass
	
	def onNews( self, event ):
		# TODO: Implement onNews
		pass
	
	def onRegister( self, event ):
		# TODO: Implement onRegister
		pass
	
	def onForgetPassword( self, event ):
		# TODO: Implement onForgetPassword
		pass
	
	
