class customString:
    def __init__(self, case):
        if case == 'forgetpw':
            self.title = u'Forget Password'
            self.id = u'ID: '
            self.email = u'Email: '
            self.resetpw = u'&Reset Password '
            self.contact = u'&Contect Admin'
            self.cancel = u'&Cancel'
        if case == 'aboutus':
            self.title = u'About Us'
            self.exit = u'&Exit'
            self.content = 'This system is developed by 404 NOT FOUND team from Hong Kong Baptist University.\n 404 NOT FOUND:\n13207296 YEUNG MAN KIT\n13205633 CHAN WING SUN\n12210102 MAK KIT TIN\n15208249 LEUNG KAI HIN'
        if case == 'reg':
            self.title = u'Register'
            self.id = u'ID: '
            self.oldpw = u'Old Password: '
            self.newpw = u'New Password: '
            self.confirmnewpw = u'Confirm New Password: '
            self.email = u'Email: '
            self.tel = u'Telephone: '
            self.save = u'&Save'
            self.cancel = u'&Cancel'
        if case == 'setting':
            self.title = u'Setting'
            self.innertitle = u'System Setting'
            self.arrowchoice1 = u'Positive : Green; Negative : Red'
            self.arrowchoice2 = u'Positive : Red; Negative : Green'
            self.refreshtime = u'Refresh Time'
            self.halfsec = u'0.5 sec'
            self.onesec = u'1 sec'
            self.twosec = u'2 sec'
        if case == 'admin':
            self.title = u'Admin'
            self.id = u'ID:'
            self.stat = u'STATISTICS'
            self.exit = u'Exit'
            self.logout = u'Logout'
            self.home = u'Home'
            self.news = u'News'
            self.search = u'Search stock'
            self.monitor = u'Monitoring Stock'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.admin = 'Admin'
        if case == 'fin':
            self.title = u'Finances News'
            self.exit = u'Exit'
            self.logout = u'Logout'
            self.home = u'Home'
            self.news = u'News'
            self.search = u'Search stock'
            self.monitor = u'Monitoring Stock'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.admin = 'Admin'
        if case == 'login':
            self.title = u'Login'
            self.id = u'ID:'
            self.pw = u'Password:'
            self.login = u'Login'
            self.reg = u'Register'
            self.forgetpw = u'Forget Password'
            self.exit = u'Exit'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.news = u'News'
        if case == 'monitor':
            self.title = u'Monitoring Stock'
            self.exit = u'Exit'
            self.logout = u'Logout'
            self.home = u'Home'
            self.news = u'News'
            self.search = u'Search stock'
            self.monitor = u'Monitoring Stock'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.admin = 'Admin'
        if case == 'search':
            self.title = u'Search Stock'
            self.searchsk = u'Search Stock'
            self.searchdef = u'000001'
            self.exit = u'Exit'
            self.logout = u'Logout'
            self.home = u'Home'
            self.news = u'News'
            self.search = u'Search stock'
            self.monitor = u'Monitoring Stock'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.admin = 'Admin'
        if case == 'home':
            self.title = u'Welcome'
            self.exit = u'Exit'
            self.logout = u'Logout'
            self.home = u'Home'
            self.news = u'News'
            self.search = u'Search stock'
            self.monitor = u'Monitoring Stock'
            self.setting = u'Setting'
            self.about = u'About Us'
            self.admin = 'Admin'

