"""Subclass of Login_frame, which is generated by wxFormBuilder."""

import wx
import Stock_Monitor

# Implementing Login_frame
class Stock_Monitoring_SystemLogin_frame( Stock_Monitor.Login_frame ):
	def __init__( self, parent ):
		Stock_Monitor.Login_frame.__init__( self, parent )
	
	# Handlers for Login_frame events.
	def onExit( self, event ):
		# TODO: Implement onExit
		pass
	
	def onLogin( self, event ):
		# TODO: Implement onLogin
		pass
	
	def onRegister( self, event ):
		# TODO: Implement onRegister
		pass
	
	def onForgetPassword( self, event ):
		# TODO: Implement onForgetPassword
		pass
	
	
